services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: "verdaccio"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./config:/verdaccio/conf"
networks:
  node-network:
    driver: bridge
